### ISSUE TITLE
YAML exceptions should indicate problematic file

### ISSUE THREAD

**Issue by yfried** [rhosqeauto/oldir#29]
> yaml.constructor.ConstructorError: could not determine a constructor for the tag '!overwrite'
>   in "<string>", line 15, column 43:
>      ...   CONFIG_NEUTRON_OVS_TUNNEL_IF: !overwrite ""

Replace `"<string>"` with actual filename

**Comment by yfried-redhat** [comment]
@ao

**Comment by yfried** [comment]
fixed by #30
